apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.repository }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.image.repository }}
  # externalIPs:
  #   - 127.0.0.1
